project:
  render:
    - index.qmd
  execute-dir: project

lang: en
title: Language
subject: Fonaments de Psicobiologia
subtitle: Structure and research methods
author: 
  - name: Gonzalo García-Castro
    github: gongcastro
    url: gongcastro.github.io
    email: gonzalo.garcia@sjd.es
    orcid: 0000-0002-8553-4209
    degrees: PhD
    affiliations:
      - name: Institut de Recerca Sant Joan de Déu (IRSJD)
      
footer: Fonaments de Psicobiologia, Màster en Neurociències, Universitat de Barcelona
    
date: 2026/09/29
date-format: long
format:
  revealjs:
    scrollable: true
    include-after-body: assets/templates/hide-footer-except-title.html
    
css: assets/style/style.scss
bibliography: assets/bibliography.bib


email-obfuscation: javascript
slide-number: c
transition: fade
transition-speed: fast

mainfont: Arial
fontsize: 1.6rem
linkcolor: blue
monofont: Fira Code
monobackgroundcolor: lightgrey
